### ISSUE TITLE
Error when using stdin

### ISSUE THREAD

**Issue by code-tree** [Robpol86/flake8-pep257#2]
Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/flake8/main.py", line 33, in main
    report = flake8_style.check_files()
  File "/usr/local/lib/python3.4/dist-packages/pep8.py", line 1832, in check_files
    runner(path)
  File "/usr/local/lib/python3.4/dist-packages/flake8/engine.py", line 95, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "/usr/local/lib/python3.4/dist-packages/pep8.py", line 1564, in check_all
    self.check_ast()
  File "/usr/local/lib/python3.4/dist-packages/pep8.py", line 1511, in check_ast
    for lineno, offset, text, check in checker.run():
  File "/usr/local/lib/python3.4/dist-packages/flake8_pep257.py", line 94, in run
    filename, source = load_file(self.filename)
  File "/usr/local/lib/python3.4/dist-packages/flake8_pep257.py", line 29, in load_file
    return 'stdin', pep8.stdin_get_value()
  File "/usr/local/lib/python3.4/dist-packages/pep8.py", line 1198, in stdin_get_value
    return TextIOWrapper(sys.stdin.buffer, errors='ignore').read()
ValueError: I/O operation on closed file

**Comment by Robpol86** [comment]
I'm having trouble reproducing this:

```
(env)[Bosco test_ignore_False_tox_ini_0]$ cat sample_module.py |flake8 -
stdin:1:1: D100 Missing docstring in public module
(env)[Bosco test_ignore_False_tox_ini_0]$ cat sample_module.py |flake8 -
stdin:1:1: D100 Missing docstring in public module
(env)[Bosco test_ignore_False_tox_ini_0]$ flake8
./sample_module.py:1:1: D100 Missing docstring in public module
./sample_module.py:5:1: D300 Use """triple double quotes""" (found '''-quotes)
./sample_module.py:5:1: D401 First line should be in imperative mood ('Print', not 'Prints')
./sample_module.py:14:1: D300 Use """triple double quotes""" (found '''-quotes)
(env)[Bosco test_ignore_False_tox_ini_0]$ flake8 sample_module.py 
sample_module.py:1:1: D100 Missing docstring in public module
sample_module.py:5:1: D300 Use """triple double quotes""" (found '''-quotes)
sample_module.py:5:1: D401 First line should be in imperative mood ('Print', not 'Prints')
sample_module.py:14:1: D300 Use """triple double quotes""" (found '''-quotes)
(env)[Bosco test_ignore_False_tox_ini_0]$ mkdir other
(env)[Bosco test_ignore_False_tox_ini_0]$ cd other/
(env)[Bosco other]$ cat ../sample_module.py |flake8 -
stdin:1:1: D100 Missing docstring in public module
(env)[Bosco other]$ 
```

Can you specify some steps I can take?

**Comment by Arcanemagus** [comment]
@code-tree your trace shows it was last in `pep8` before the issue, are you sure this is caused by `flake8-pep257`?

**Comment by lunaryorn** [comment]
I can reproduce the issue.  I don't know what causes this, but if I `pip uninstall flake8-pep257` the issue is gone, which makes me assume that it's caused by `flake8-pep257`.

At a superficial look at the source code of this plugin it seems that it reads the file again, which fails on standard input because it's a “one-time” stream.

**Comment by code-tree** [comment]
I came to the same conclusion as @lunaryorn. I got a bit lost when trying to figure out whether that was flake8, pep8, or pep257's fault, but same as @lunaryorn, it works fine when I remove pep257.

**Comment by Robpol86** [comment]
What command are you all running? How are you using flake8-pep257? Do you just run `flake8`? If so can you tell me the output of `pip freeze` and `pip --version`?

**Comment by lunaryorn** [comment]
@Robpol86 I can even give you an entire recipe to reproduce the issue:

```
$ mkvirtualenv flake8-demo
Using base prefix '/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5'
New python executable in flake8-demo/bin/python3.5
Also creating executable in flake8-demo/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating ${HOME}/.virtualenvs/flake8-demo/bin/predeactivate
virtualenvwrapper.user_scripts creating ${HOME}/.virtualenvs/flake8-demo/bin/postdeactivate
virtualenvwrapper.user_scripts creating ${HOME}/.virtualenvs/flake8-demo/bin/preactivate
virtualenvwrapper.user_scripts creating ${HOME}/.virtualenvs/flake8-demo/bin/postactivate
virtualenvwrapper.user_scripts creating ${HOME}/.virtualenvs/flake8-demo/bin/get_env_details
$ pip install flake8 flake8-pep257
Collecting flake8
  Using cached flake8-2.5.0-py2.py3-none-any.whl
Collecting flake8-pep257
Collecting pep8!=1.6.0,!=1.6.1,!=1.6.2,>=1.5.7 (from flake8)
  Using cached pep8-1.5.7-py2.py3-none-any.whl
Collecting mccabe<0.4,>=0.2.1 (from flake8)
  Using cached mccabe-0.3.1-py2.py3-none-any.whl
Collecting pyflakes<1.1,>=0.8.1 (from flake8)
  Using cached pyflakes-1.0.0-py2.py3-none-any.whl
Collecting pep257 (from flake8-pep257)
  Using cached pep257-0.7.0-py2.py3-none-any.whl
Installing collected packages: pep8, mccabe, pyflakes, flake8, pep257, flake8-pep257
Successfully installed flake8-2.5.0 flake8-pep257-1.0.4 mccabe-0.3.1 pep257-0.7.0 pep8-1.5.7 pyflakes-1.0.0
% hash -r
% flake8 --version
2.5.0 (pep8: 1.5.7, pyflakes: 1.0.0, flake8-pep257: 1.0.4, mccabe: 0.3.1) CPython 3.5.0 on Darwin
% cat foo.py
def spam():
    print('Spam with eggs')

def hello():
    print("  " )
$ flake8 foo.py
foo.py:1:1: D100 Missing docstring in public module
foo.py:1:1: D103 Missing docstring in public function
foo.py:4:1: D103 Missing docstring in public function
foo.py:4:1: E302 expected 2 blank lines, found 1
foo.py:5:15: E202 whitespace before ')'
$ flake8 - < foo.py
Traceback (most recent call last):
  File "${HOME}/.virtualenvs/flake8-demo/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "${HOME}/.virtualenvs/flake8-demo/lib/python3.5/site-packages/flake8/main.py", line 33, in main
    report = flake8_style.check_files()
  File "${HOME}/.virtualenvs/flake8-demo/lib/python3.5/site-packages/flake8/engine.py", line 176, in check_files
    return self._retry_serial(self._styleguide.check_files, paths=paths)
  File "${HOME}/.virtualenvs/flake8-demo/lib/python3.5/site-packages/flake8/engine.py", line 167, in _retry_serial
    return func(*args, **kwargs)
  File "${HOME}/.virtualenvs/flake8-demo/lib/python3.5/site-packages/pep8.py", line 1672, in check_files
    runner(path)
  File "${HOME}/.virtualenvs/flake8-demo/lib/python3.5/site-packages/flake8/engine.py", line 121, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "${HOME}/.virtualenvs/flake8-demo/lib/python3.5/site-packages/pep8.py", line 1412, in check_all
    self.check_ast()
  File "${HOME}/.virtualenvs/flake8-demo/lib/python3.5/site-packages/pep8.py", line 1359, in check_ast
    for lineno, offset, text, check in checker.run():
  File "${HOME}/.virtualenvs/flake8-demo/lib/python3.5/site-packages/flake8_pep257.py", line 102, in run
    filename, source = load_file(self.filename)
  File "${HOME}/.virtualenvs/flake8-demo/lib/python3.5/site-packages/flake8_pep257.py", line 26, in load_file
    return 'stdin', pep8.stdin_get_value()
  File "${HOME}/.virtualenvs/flake8-demo/lib/python3.5/site-packages/pep8.py", line 1060, in stdin_get_value
    return TextIOWrapper(sys.stdin.buffer, errors='ignore').read()
ValueError: I/O operation on closed file
$ pip freeze
flake8==2.5.0
flake8-pep257==1.0.4
mccabe==0.3.1
pep257==0.7.0
pep8==1.5.7
pyflakes==1.0.0
wheel==0.24.0
```

I've substituted my home directory path with ${HOME}, but other than that the output is unmodified.

**Comment by Robpol86** [comment]
Thanks @lunaryorn this is exactly what I was looking for. I was able to reproduce it with py3.4 on my mac (2.7 worked fine). I'll work on a fix hopefully this weekend.

**Comment by lunaryorn** [comment]
@Robpol86 You're welcome :relaxed:  Thank you for taking a look at this :+1:

**Comment by code-tree** [comment]
Impressive work around!

Works for me... thanks :)

**Comment by code-tree** [comment]
Should maybe report that limitation to flake8, so they can provide a better solution in future?

**Comment by deanyanqing** [comment]
Works for me.Thanks.
And same issue in line 43 of flake8_docstrings.py

**Comment by lunaryorn** [comment]
@deanyanqing You need to report that to the maintainer of that plugin.

**Comment by Arcanemagus** [comment]
@Robpol86 you might be interested in this: [pep8-stdin-fix](https://gitlab.com/pycqa/flake8/commit/d5e3987a9c41ae8cd007fe21f6aeb5e972ad0d3d).

@sigmavirus24 patched in a function into pep8 through flake8 to get the stdin input directly.

**Comment by Robpol86** [comment]
Nice! I'll check it out once it's released.

**Comment by Robpol86** [comment]
Actually now that I look at it, the exception was being raised by pep8.stdin_get_value(). That commit still uses the function and doesn't wrap it in a try/except.
