### ISSUE TITLE
pep257 gets confused about spaces in class documentation

### ISSUE THREAD

**Issue by jbiason** [Robpol86/flake8-pep257#5]
The following piece of code:

    class FakeResponse(object):           # pylint:disable=too-few-public-methods

        """A fake HTTPResponse object (which we can't create ourselves)."""

        def __init__(self):
            pass

Gets error `D211 No blank lines allowed before class docstring (found 1)`. But, if you remove the blank line before the docstring, you get `D203 1 blank line required before class docstring (found 0)`, which is confusing as hell.

**Comment by Korijn** [comment]
I noticed this too. I guess you just need to add one to your ignore list and stick with that convention.

**Comment by Robpol86** [comment]
Yea you'll just need to add one to your ignore list like Korijn said.

```
$ pep257 .
./file.py:3 in public class `FakeResponse`:
        D211: No blank lines allowed before class docstring (found 1)
./file.py:7 in public method `__init__`:
        D102: Missing docstring in public method
```

Not really something I can/should fix, just a side effect of bringing together two independently developed projects (pep257 and flake8).

I always put `ignore = D203` in my ini/cfg files in all of my projects.
